### ISSUE TITLE
`Icons.dll` source

### ISSUE THREAD

**Issue by pa-0** [XMCQCX/WinExeCommander#1]
Can you share the source for Icons.dll?

**Comment by XMCQCX** [comment]
@pa-0 I assume you want to extract the icons? I created it using 'Resource Hacker.' You can extract them with this tool:
- Open Resource Hacker.
- Click on Open
- Select Icons.dll
- Expand the Icon Group.
- Click on the desired icon.
- Right-click and choose Save *.ico resource....

**Comment by pa-0** [comment]
If I were to replace the dll with the extracted ico files in the AHK scripts, would the scripts have everything needed to run, or is there anything else in that dll that's required by WinExeCommander?

**Comment by XMCQCX** [comment]
@pa-0 'Icons.dll' contains only icons and is required for the script to run, it will not start without it.

**Comment by pa-0** [comment]
Thanks!
